spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

smartcart.maps.provider=google
smartcart.maps.google.api-key=${GOOGLE_MAPS_API_KEY:}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.springframework.security=INFO